- name: Homzhub
  tag: Product Manager
  link: https://www.homzhub.com/
  position: 1
  time: "2017-2021"
  description: "We at Homzhub have launched mobile and web apps for real estate investors around the world. Our Apps are being used by 5000 property investors around the world."

- name: Particypants
  tag: Founder
  link: https://www.particypants.com/
  position: 2
  time: "2021"
  description: "A slack application to organise meeting notes. I created this in ruby on rails. Right now at a stage where I am trying onboard early adopters."

- name: 1940Seven
  tag: Co-founder
  link: http://1940seven.com/
  time: "2021"
  position: 3
  description: "A e-commerce marketplace for international creators to sell their merchandise to Indian consumers."

- name: EaseBox
  tag: Co-founder
  link: https://easebox.in/
  time: "2020"
  position: 4
  description: "Helping working professionals move into a new city. With easebox, you can buy entire boxes to easily setup your new home."

- name: Better Product Manager
  tag: Blog
  link: https://betterproductmanager.com/
  position: 5
  time: "2019"
  description: "This is my idea of working with my garage door up. I am writing these journals, to reflect and become a better product manager and by practice a better note-taker."

- name: Real Estate App
  tag: Closed
  link: https://github.com/vedant14/realEstate
  position: 6
  time: "2019"
  description: "The idea was to create a real estate listing app that agents can use to market their properties. I used to call 100s of agents everyday tring to onboard them but could not convert any."

- name: Trendy Turn
  tag: Closed
  link: https://www.trendyturn.com
  position: 7
  time: "2019"
  description: "My first freelance project which was unfortunately closed down. But I earned decent money and learned a ton."

- name: Personal Finance Course Site
  tag: Freelance
  link: https://finance.aggyabhishek.com/
  position: 8
  time: "2021"
  description: "Created a landing page for Abhishek's site."
